

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Steel(object):
    def setupUi(self, Steel):
        Steel.setObjectName("Steel")
        Steel.resize(1362, 706)
        self.pushButton = QtWidgets.QPushButton(Steel)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Steel)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar.setGeometry(QtCore.QRect(880, 50, 20, 281))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.lineEdit = QtWidgets.QLineEdit(Steel)
        self.lineEdit.setGeometry(QtCore.QRect(650, 350, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_2.setGeometry(QtCore.QRect(650, 380, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_3.setGeometry(QtCore.QRect(650, 410, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_4.setGeometry(QtCore.QRect(650, 440, 61, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_5.setGeometry(QtCore.QRect(650, 470, 61, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_6.setGeometry(QtCore.QRect(650, 500, 61, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_7.setGeometry(QtCore.QRect(650, 530, 61, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_8.setGeometry(QtCore.QRect(650, 560, 61, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_9.setGeometry(QtCore.QRect(650, 590, 61, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_10.setGeometry(QtCore.QRect(650, 620, 61, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_11.setGeometry(QtCore.QRect(850, 470, 61, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_12.setGeometry(QtCore.QRect(850, 380, 61, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_13.setGeometry(QtCore.QRect(850, 440, 61, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_14.setGeometry(QtCore.QRect(850, 410, 61, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_15.setGeometry(QtCore.QRect(850, 620, 61, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_16.setGeometry(QtCore.QRect(850, 530, 61, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_17.setGeometry(QtCore.QRect(850, 560, 61, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_18.setGeometry(QtCore.QRect(850, 500, 61, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_19.setGeometry(QtCore.QRect(850, 590, 61, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label = QtWidgets.QLabel(Steel)
        self.label.setGeometry(QtCore.QRect(616, 350, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Steel)
        self.label_2.setGeometry(QtCore.QRect(580, 370, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Steel)
        self.label_3.setGeometry(QtCore.QRect(606, 410, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Steel)
        self.label_4.setGeometry(QtCore.QRect(606, 440, 31, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Steel)
        self.label_5.setGeometry(QtCore.QRect(617, 470, 20, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Steel)
        self.label_6.setGeometry(QtCore.QRect(617, 500, 20, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Steel)
        self.label_7.setGeometry(QtCore.QRect(616, 530, 21, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Steel)
        self.label_8.setGeometry(QtCore.QRect(617, 560, 20, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Steel)
        self.label_9.setGeometry(QtCore.QRect(580, 590, 61, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Steel)
        self.label_10.setGeometry(QtCore.QRect(616, 620, 21, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Steel)
        self.label_11.setGeometry(QtCore.QRect(816, 440, 21, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Steel)
        self.label_12.setGeometry(QtCore.QRect(816, 470, 21, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Steel)
        self.label_13.setGeometry(QtCore.QRect(800, 620, 41, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Steel)
        self.label_14.setGeometry(QtCore.QRect(816, 560, 21, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Steel)
        self.label_15.setGeometry(QtCore.QRect(816, 530, 21, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Steel)
        self.label_16.setGeometry(QtCore.QRect(816, 410, 21, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Steel)
        self.label_17.setGeometry(QtCore.QRect(817, 590, 20, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Steel)
        self.label_18.setGeometry(QtCore.QRect(816, 500, 21, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Steel)
        self.label_19.setGeometry(QtCore.QRect(816, 380, 21, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Steel)
        self.label_20.setGeometry(QtCore.QRect(816, 350, 21, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Steel)
        self.label_21.setGeometry(QtCore.QRect(740, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit.setGeometry(QtCore.QRect(700, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_3 = QtWidgets.QPushButton(Steel)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 110, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Steel)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 140, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Steel)
        self.pushButton_6.setGeometry(QtCore.QRect(570, 80, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_20 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_20.setGeometry(QtCore.QRect(850, 350, 61, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_21.setGeometry(QtCore.QRect(234, 620, 61, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_22 = QtWidgets.QLabel(Steel)
        self.label_22.setGeometry(QtCore.QRect(200, 620, 21, 20))
        self.label_22.setObjectName("label_22")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(284, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_23 = QtWidgets.QLabel(Steel)
        self.label_23.setGeometry(QtCore.QRect(400, 440, 21, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Steel)
        self.label_24.setGeometry(QtCore.QRect(200, 680, 21, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_22 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_22.setGeometry(QtCore.QRect(234, 590, 61, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_24 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_24.setGeometry(QtCore.QRect(234, 470, 61, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_25 = QtWidgets.QLabel(Steel)
        self.label_25.setGeometry(QtCore.QRect(380, 530, 41, 20))
        self.label_25.setObjectName("label_25")
        self.pushButton_5 = QtWidgets.QPushButton(Steel)
        self.pushButton_5.setGeometry(QtCore.QRect(154, 110, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_26 = QtWidgets.QLabel(Steel)
        self.label_26.setGeometry(QtCore.QRect(380, 410, 41, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Steel)
        self.label_27.setGeometry(QtCore.QRect(194, 590, 31, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Steel)
        self.label_28.setGeometry(QtCore.QRect(190, 410, 31, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Steel)
        self.label_29.setGeometry(QtCore.QRect(201, 560, 20, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_25 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_25.setGeometry(QtCore.QRect(234, 650, 61, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_26.setGeometry(QtCore.QRect(234, 380, 61, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_27.setGeometry(QtCore.QRect(234, 500, 61, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_28.setGeometry(QtCore.QRect(234, 410, 61, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_30 = QtWidgets.QLabel(Steel)
        self.label_30.setGeometry(QtCore.QRect(201, 500, 20, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Steel)
        self.label_31.setGeometry(QtCore.QRect(190, 650, 31, 20))
        self.label_31.setObjectName("label_31")
        self.pushButton_7 = QtWidgets.QPushButton(Steel)
        self.pushButton_7.setGeometry(QtCore.QRect(154, 80, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Steel)
        self.pushButton_8.setGeometry(QtCore.QRect(154, 50, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_32 = QtWidgets.QLabel(Steel)
        self.label_32.setGeometry(QtCore.QRect(200, 350, 21, 20))
        self.label_32.setObjectName("label_32")
        self.lineEdit_30 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_30.setGeometry(QtCore.QRect(234, 530, 61, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_33 = QtWidgets.QLabel(Steel)
        self.label_33.setGeometry(QtCore.QRect(380, 500, 41, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Steel)
        self.label_34.setGeometry(QtCore.QRect(394, 560, 31, 20))
        self.label_34.setObjectName("label_34")
        self.lineEdit_32 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_32.setGeometry(QtCore.QRect(234, 440, 61, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_35 = QtWidgets.QLabel(Steel)
        self.label_35.setGeometry(QtCore.QRect(164, 370, 61, 31))
        self.label_35.setObjectName("label_35")
        self.lineEdit_34 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_34.setGeometry(QtCore.QRect(234, 560, 61, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_36 = QtWidgets.QLabel(Steel)
        self.label_36.setGeometry(QtCore.QRect(200, 530, 21, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Steel)
        self.label_37.setGeometry(QtCore.QRect(400, 470, 21, 20))
        self.label_37.setObjectName("label_37")
        self.lineEdit_36 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_36.setGeometry(QtCore.QRect(234, 680, 61, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_38 = QtWidgets.QLabel(Steel)
        self.label_38.setGeometry(QtCore.QRect(324, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Steel)
        self.label_39.setGeometry(QtCore.QRect(190, 440, 31, 20))
        self.label_39.setObjectName("label_39")
        self.pushButton_9 = QtWidgets.QPushButton(Steel)
        self.pushButton_9.setGeometry(QtCore.QRect(154, 140, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_40 = QtWidgets.QLabel(Steel)
        self.label_40.setGeometry(QtCore.QRect(190, 470, 31, 20))
        self.label_40.setObjectName("label_40")
        self.lineEdit_39 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_39.setGeometry(QtCore.QRect(234, 350, 61, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_41 = QtWidgets.QLabel(Steel)
        self.label_41.setGeometry(QtCore.QRect(400, 350, 21, 20))
        self.label_41.setObjectName("label_41")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(464, 50, 20, 281))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.label_42 = QtWidgets.QLabel(Steel)
        self.label_42.setGeometry(QtCore.QRect(380, 380, 41, 20))
        self.label_42.setObjectName("label_42")
        self.lineEdit_41 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_41.setGeometry(QtCore.QRect(1084, 620, 61, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_43 = QtWidgets.QLabel(Steel)
        self.label_43.setGeometry(QtCore.QRect(1050, 620, 21, 20))
        self.label_43.setObjectName("label_43")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(1124, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_44 = QtWidgets.QLabel(Steel)
        self.label_44.setGeometry(QtCore.QRect(1250, 500, 21, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(Steel)
        self.label_45.setGeometry(QtCore.QRect(1250, 380, 21, 20))
        self.label_45.setObjectName("label_45")
        self.lineEdit_42 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_42.setGeometry(QtCore.QRect(1084, 590, 61, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_43.setGeometry(QtCore.QRect(1284, 530, 61, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_44.setGeometry(QtCore.QRect(1084, 470, 61, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.label_46 = QtWidgets.QLabel(Steel)
        self.label_46.setGeometry(QtCore.QRect(1251, 590, 20, 20))
        self.label_46.setObjectName("label_46")
        self.pushButton_10 = QtWidgets.QPushButton(Steel)
        self.pushButton_10.setGeometry(QtCore.QRect(994, 110, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_47 = QtWidgets.QLabel(Steel)
        self.label_47.setGeometry(QtCore.QRect(1250, 470, 21, 20))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(Steel)
        self.label_48.setGeometry(QtCore.QRect(1014, 590, 61, 20))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Steel)
        self.label_49.setGeometry(QtCore.QRect(1040, 410, 31, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(Steel)
        self.label_50.setGeometry(QtCore.QRect(1051, 560, 20, 20))
        self.label_50.setObjectName("label_50")
        self.lineEdit_45 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_45.setGeometry(QtCore.QRect(1284, 350, 61, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_46.setGeometry(QtCore.QRect(1084, 380, 61, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_47.setGeometry(QtCore.QRect(1084, 500, 61, 20))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_48.setGeometry(QtCore.QRect(1084, 410, 61, 20))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.label_51 = QtWidgets.QLabel(Steel)
        self.label_51.setGeometry(QtCore.QRect(1051, 500, 20, 20))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Steel)
        self.label_52.setGeometry(QtCore.QRect(1250, 350, 21, 20))
        self.label_52.setObjectName("label_52")
        self.lineEdit_49 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_49.setGeometry(QtCore.QRect(1284, 590, 61, 20))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.pushButton_11 = QtWidgets.QPushButton(Steel)
        self.pushButton_11.setGeometry(QtCore.QRect(994, 80, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Steel)
        self.pushButton_12.setGeometry(QtCore.QRect(994, 50, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_53 = QtWidgets.QLabel(Steel)
        self.label_53.setGeometry(QtCore.QRect(1050, 350, 21, 20))
        self.label_53.setObjectName("label_53")
        self.lineEdit_50 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_50.setGeometry(QtCore.QRect(1084, 530, 61, 20))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_54 = QtWidgets.QLabel(Steel)
        self.label_54.setGeometry(QtCore.QRect(1250, 560, 21, 20))
        self.label_54.setObjectName("label_54")
        self.lineEdit_51 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_51.setGeometry(QtCore.QRect(1284, 500, 61, 20))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.label_55 = QtWidgets.QLabel(Steel)
        self.label_55.setGeometry(QtCore.QRect(1234, 620, 41, 20))
        self.label_55.setObjectName("label_55")
        self.lineEdit_52 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_52.setGeometry(QtCore.QRect(1084, 440, 61, 20))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.label_56 = QtWidgets.QLabel(Steel)
        self.label_56.setGeometry(QtCore.QRect(1014, 370, 61, 31))
        self.label_56.setObjectName("label_56")
        self.lineEdit_53 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_53.setGeometry(QtCore.QRect(1284, 440, 61, 20))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_54.setGeometry(QtCore.QRect(1084, 560, 61, 20))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.label_57 = QtWidgets.QLabel(Steel)
        self.label_57.setGeometry(QtCore.QRect(1050, 530, 21, 20))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Steel)
        self.label_58.setGeometry(QtCore.QRect(1250, 530, 21, 20))
        self.label_58.setObjectName("label_58")
        self.lineEdit_55 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_55.setGeometry(QtCore.QRect(1284, 560, 61, 20))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_56.setGeometry(QtCore.QRect(1284, 380, 61, 20))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_57.setGeometry(QtCore.QRect(1284, 410, 61, 20))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.label_59 = QtWidgets.QLabel(Steel)
        self.label_59.setGeometry(QtCore.QRect(1164, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.lineEdit_58 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_58.setGeometry(QtCore.QRect(1284, 620, 61, 20))
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.label_60 = QtWidgets.QLabel(Steel)
        self.label_60.setGeometry(QtCore.QRect(1040, 440, 31, 20))
        self.label_60.setObjectName("label_60")
        self.pushButton_13 = QtWidgets.QPushButton(Steel)
        self.pushButton_13.setGeometry(QtCore.QRect(994, 140, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_61 = QtWidgets.QLabel(Steel)
        self.label_61.setGeometry(QtCore.QRect(1051, 470, 20, 20))
        self.label_61.setObjectName("label_61")
        self.lineEdit_59 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_59.setGeometry(QtCore.QRect(1084, 350, 61, 20))
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.label_62 = QtWidgets.QLabel(Steel)
        self.label_62.setGeometry(QtCore.QRect(1250, 410, 21, 20))
        self.label_62.setObjectName("label_62")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(1304, 50, 20, 281))
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.lineEdit_60 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_60.setGeometry(QtCore.QRect(1284, 470, 61, 20))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.label_63 = QtWidgets.QLabel(Steel)
        self.label_63.setGeometry(QtCore.QRect(1250, 440, 21, 20))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(Steel)
        self.label_64.setGeometry(QtCore.QRect(340, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(Steel)
        self.label_65.setGeometry(QtCore.QRect(760, 10, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(Steel)
        self.label_66.setGeometry(QtCore.QRect(1190, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.line = QtWidgets.QFrame(Steel)
        self.line.setGeometry(QtCore.QRect(523, 0, 20, 711))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Steel)
        self.line_2.setGeometry(QtCore.QRect(950, -10, 20, 721))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Steel)
        self.line_3.setGeometry(QtCore.QRect(110, -10, 20, 721))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_23 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_23.setGeometry(QtCore.QRect(430, 590, 61, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_29 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_29.setGeometry(QtCore.QRect(430, 380, 61, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_31 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_31.setGeometry(QtCore.QRect(430, 620, 61, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_37 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_37.setGeometry(QtCore.QRect(430, 680, 61, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_40 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_40.setGeometry(QtCore.QRect(430, 350, 61, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_33 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_33.setGeometry(QtCore.QRect(430, 410, 61, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_35 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_35.setGeometry(QtCore.QRect(430, 650, 61, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_38 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_38.setGeometry(QtCore.QRect(430, 560, 61, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_61 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_61.setGeometry(QtCore.QRect(430, 500, 61, 20))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_62 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_62.setGeometry(QtCore.QRect(430, 470, 61, 20))
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_63.setGeometry(QtCore.QRect(430, 530, 61, 20))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_64.setGeometry(QtCore.QRect(430, 440, 61, 20))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.label_67 = QtWidgets.QLabel(Steel)
        self.label_67.setGeometry(QtCore.QRect(396, 590, 21, 20))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(Steel)
        self.label_68.setGeometry(QtCore.QRect(396, 620, 21, 20))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(Steel)
        self.label_69.setGeometry(QtCore.QRect(390, 650, 20, 20))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(Steel)
        self.label_70.setGeometry(QtCore.QRect(380, 680, 41, 20))
        self.label_70.setObjectName("label_70")
        self.lineEdit_65 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_65.setGeometry(QtCore.QRect(1084, 650, 61, 20))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.label_71 = QtWidgets.QLabel(Steel)
        self.label_71.setGeometry(QtCore.QRect(1050, 650, 21, 20))
        self.label_71.setObjectName("label_71")
        self.pushButton_14 = QtWidgets.QPushButton(Steel)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")

        self.retranslateUi(Steel)
        QtCore.QMetaObject.connectSlotsByName(Steel)

    def retranslateUi(self, Steel):
        _translate = QtCore.QCoreApplication.translate
        Steel.setWindowTitle(_translate("Steel", "Dialog"))
        self.pushButton.setText(_translate("Steel", "Load Data"))
        self.pushButton_2.setText(_translate("Steel", "Update"))
        self.label.setText(_translate("Steel", "ID"))
        self.label_2.setText(_translate("Steel", "Designation"))
        self.label_3.setText(_translate("Steel", "Mass"))
        self.label_4.setText(_translate("Steel", "Area"))
        self.label_5.setText(_translate("Steel", "D"))
        self.label_6.setText(_translate("Steel", "B"))
        self.label_7.setText(_translate("Steel", "tw"))
        self.label_8.setText(_translate("Steel", "T"))
        self.label_9.setText(_translate("Steel", "FlangeSlope"))
        self.label_10.setText(_translate("Steel", "R1"))
        self.label_11.setText(_translate("Steel", "rz"))
        self.label_12.setText(_translate("Steel", "ry"))
        self.label_13.setText(_translate("Steel", "Source"))
        self.label_14.setText(_translate("Steel", "Zpz"))
        self.label_15.setText(_translate("Steel", "Zy"))
        self.label_16.setText(_translate("Steel", "ly"))
        self.label_17.setText(_translate("Steel", "Zpy"))
        self.label_18.setText(_translate("Steel", "Zz"))
        self.label_19.setText(_translate("Steel", "lz"))
        self.label_20.setText(_translate("Steel", "R2"))
        self.label_21.setText(_translate("Steel", "   Designation"))
        self.pushButton_3.setText(_translate("Steel", "Add"))
        self.pushButton_4.setText(_translate("Steel", "Import"))
        self.pushButton_6.setText(_translate("Steel", "Clear Field"))
        self.label_22.setText(_translate("Steel", "Cy"))
        self.label_23.setText(_translate("Steel", "rz"))
        self.label_24.setText(_translate("Steel", "lz"))
        self.label_25.setText(_translate("Steel", "ru(min)"))
        self.pushButton_5.setText(_translate("Steel", "Add"))
        self.label_26.setText(_translate("Steel", "lv(min)"))
        self.label_27.setText(_translate("Steel", "  Cz"))
        self.label_28.setText(_translate("Steel", "Mass"))
        self.label_29.setText(_translate("Steel", "R2"))
        self.label_30.setText(_translate("Steel", "t"))
        self.label_31.setText(_translate("Steel", "Tan?"))
        self.pushButton_7.setText(_translate("Steel", "Clear Field"))
        self.pushButton_8.setText(_translate("Steel", "Update"))
        self.label_32.setText(_translate("Steel", "ID"))
        self.label_33.setText(_translate("Steel", "ru(max)"))
        self.label_34.setText(_translate("Steel", "Zz"))
        self.label_35.setText(_translate("Steel", "Designation"))
        self.label_36.setText(_translate("Steel", "R1"))
        self.label_37.setText(_translate("Steel", "ry"))
        self.label_38.setText(_translate("Steel", "   Designation"))
        self.label_39.setText(_translate("Steel", "Area"))
        self.pushButton_9.setText(_translate("Steel", "Import"))
        self.label_40.setText(_translate("Steel", "AXB"))
        self.label_41.setText(_translate("Steel", "ly"))
        self.label_42.setText(_translate("Steel", "lu(max)"))
        self.label_43.setText(_translate("Steel", "R1"))
        self.label_44.setText(_translate("Steel", "Zz"))
        self.label_45.setText(_translate("Steel", "lz"))
        self.label_46.setText(_translate("Steel", "Zpy"))
        self.pushButton_10.setText(_translate("Steel", "Add"))
        self.label_47.setText(_translate("Steel", "ry"))
        self.label_48.setText(_translate("Steel", "FlangeSlope"))
        self.label_49.setText(_translate("Steel", "Mass"))
        self.label_50.setText(_translate("Steel", "T"))
        self.label_51.setText(_translate("Steel", "B"))
        self.label_52.setText(_translate("Steel", "R2"))
        self.pushButton_11.setText(_translate("Steel", "Clear Field"))
        self.pushButton_12.setText(_translate("Steel", "Update"))
        self.label_53.setText(_translate("Steel", "ID"))
        self.label_54.setText(_translate("Steel", "Zpz"))
        self.label_55.setText(_translate("Steel", "Source"))
        self.label_56.setText(_translate("Steel", "Designation"))
        self.label_57.setText(_translate("Steel", "tw"))
        self.label_58.setText(_translate("Steel", "Zy"))
        self.label_59.setText(_translate("Steel", "   Designation"))
        self.label_60.setText(_translate("Steel", "Area"))
        self.pushButton_13.setText(_translate("Steel", "Import"))
        self.label_61.setText(_translate("Steel", "D"))
        self.label_62.setText(_translate("Steel", "ly"))
        self.label_63.setText(_translate("Steel", "rz"))
        self.label_64.setText(_translate("Steel", "   Angles"))
        self.label_65.setText(_translate("Steel", "  Beams"))
        self.label_66.setText(_translate("Steel", "Channels"))
        self.label_67.setText(_translate("Steel", "Zy"))
        self.label_68.setText(_translate("Steel", "Zpz"))
        self.label_69.setText(_translate("Steel", "Zpy"))
        self.label_70.setText(_translate("Steel", "Source"))
        self.label_71.setText(_translate("Steel", "Cy"))
        self.pushButton_14.setText(_translate("Steel", "Exit"))

