

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Steel(object):
    def setupUi(self, Steel):
        Steel.setObjectName("Steel")
        Steel.resize(1362, 706)
        self.pushButton_loaddata = QtWidgets.QPushButton(Steel)
        self.pushButton_loaddata.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.pushButton_loaddata.setObjectName("pushButton_loaddata")
        self.pushButton_b_update = QtWidgets.QPushButton(Steel)
        self.pushButton_b_update.setGeometry(QtCore.QRect(570, 50, 75, 23))
        self.pushButton_b_update.setObjectName("pushButton_b_update")
        self.verticalScrollBar = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar.setGeometry(QtCore.QRect(880, 50, 20, 281))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.lineEdit_200 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_200.setGeometry(QtCore.QRect(650, 350, 61, 20))
        self.lineEdit_200.setObjectName("lineEdit_200")
        self.lineEdit_201 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_201.setGeometry(QtCore.QRect(650, 380, 61, 20))
        self.lineEdit_201.setObjectName("lineEdit_201")
        self.lineEdit_202 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_202.setGeometry(QtCore.QRect(650, 410, 61, 20))
        self.lineEdit_202.setObjectName("lineEdit_202")
        self.lineEdit_203 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_203.setGeometry(QtCore.QRect(650, 440, 61, 20))
        self.lineEdit_203.setObjectName("lineEdit_203")
        self.lineEdit_204 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_204.setGeometry(QtCore.QRect(650, 470, 61, 20))
        self.lineEdit_204.setObjectName("lineEdit_204")
        self.lineEdit_205 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_205.setGeometry(QtCore.QRect(650, 500, 61, 20))
        self.lineEdit_205.setObjectName("lineEdit_205")
        self.lineEdit_206 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_206.setGeometry(QtCore.QRect(650, 530, 61, 20))
        self.lineEdit_206.setObjectName("lineEdit_206")
        self.lineEdit_207 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_207.setGeometry(QtCore.QRect(650, 560, 61, 20))
        self.lineEdit_207.setObjectName("lineEdit_207")
        self.lineEdit_208 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_208.setGeometry(QtCore.QRect(650, 590, 61, 20))
        self.lineEdit_208.setObjectName("lineEdit_208")
        self.lineEdit_209 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_209.setGeometry(QtCore.QRect(650, 620, 61, 20))
        self.lineEdit_209.setObjectName("lineEdit_209")
        self.lineEdit_214 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_214.setGeometry(QtCore.QRect(850, 470, 61, 20))
        self.lineEdit_214.setObjectName("lineEdit_214")
        self.lineEdit_211 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_211.setGeometry(QtCore.QRect(850, 380, 61, 20))
        self.lineEdit_211.setObjectName("lineEdit_211")
        self.lineEdit_213 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_213.setGeometry(QtCore.QRect(850, 440, 61, 20))
        self.lineEdit_213.setObjectName("lineEdit_213")
        self.lineEdit_212 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_212.setGeometry(QtCore.QRect(850, 410, 61, 20))
        self.lineEdit_212.setObjectName("lineEdit_212")
        self.lineEdit_219 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_219.setGeometry(QtCore.QRect(850, 620, 61, 20))
        self.lineEdit_219.setObjectName("lineEdit_219")
        self.lineEdit_216 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_216.setGeometry(QtCore.QRect(850, 530, 61, 20))
        self.lineEdit_216.setObjectName("lineEdit_216")
        self.lineEdit_217 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_217.setGeometry(QtCore.QRect(850, 560, 61, 20))
        self.lineEdit_217.setObjectName("lineEdit_217")
        self.lineEdit_215 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_215.setGeometry(QtCore.QRect(850, 500, 61, 20))
        self.lineEdit_215.setObjectName("lineEdit_215")
        self.lineEdit_218 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_218.setGeometry(QtCore.QRect(850, 590, 61, 20))
        self.lineEdit_218.setObjectName("lineEdit_218")
        self.label = QtWidgets.QLabel(Steel)
        self.label.setGeometry(QtCore.QRect(616, 350, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Steel)
        self.label_2.setGeometry(QtCore.QRect(580, 370, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Steel)
        self.label_3.setGeometry(QtCore.QRect(606, 410, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Steel)
        self.label_4.setGeometry(QtCore.QRect(606, 440, 31, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Steel)
        self.label_5.setGeometry(QtCore.QRect(617, 470, 20, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Steel)
        self.label_6.setGeometry(QtCore.QRect(617, 500, 20, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Steel)
        self.label_7.setGeometry(QtCore.QRect(616, 530, 21, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Steel)
        self.label_8.setGeometry(QtCore.QRect(617, 560, 20, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Steel)
        self.label_9.setGeometry(QtCore.QRect(580, 590, 61, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Steel)
        self.label_10.setGeometry(QtCore.QRect(616, 620, 21, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Steel)
        self.label_11.setGeometry(QtCore.QRect(816, 440, 21, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Steel)
        self.label_12.setGeometry(QtCore.QRect(816, 470, 21, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Steel)
        self.label_13.setGeometry(QtCore.QRect(800, 620, 41, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Steel)
        self.label_14.setGeometry(QtCore.QRect(816, 560, 21, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Steel)
        self.label_15.setGeometry(QtCore.QRect(816, 530, 21, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Steel)
        self.label_16.setGeometry(QtCore.QRect(816, 410, 21, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Steel)
        self.label_17.setGeometry(QtCore.QRect(817, 590, 20, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Steel)
        self.label_18.setGeometry(QtCore.QRect(816, 500, 21, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Steel)
        self.label_19.setGeometry(QtCore.QRect(816, 380, 21, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Steel)
        self.label_20.setGeometry(QtCore.QRect(816, 350, 21, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Steel)
        self.label_21.setGeometry(QtCore.QRect(740, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.plainTextEdit_beam = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit_beam.setGeometry(QtCore.QRect(700, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_beam.setFont(font)
        self.plainTextEdit_beam.setObjectName("plainTextEdit_beam")
        self.pushButton_b_add = QtWidgets.QPushButton(Steel)
        self.pushButton_b_add.setGeometry(QtCore.QRect(570, 110, 75, 23))
        self.pushButton_b_add.setObjectName("pushButton_b_add")
        self.pushButton_b_import = QtWidgets.QPushButton(Steel)
        self.pushButton_b_import.setGeometry(QtCore.QRect(570, 140, 75, 23))
        self.pushButton_b_import.setObjectName("pushButton_b_import")
        self.pushButton_b_cf = QtWidgets.QPushButton(Steel)
        self.pushButton_b_cf.setGeometry(QtCore.QRect(570, 80, 75, 23))
        self.pushButton_b_cf.setObjectName("pushButton_b_cf")
        self.lineEdit_210 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_210.setGeometry(QtCore.QRect(850, 350, 61, 20))
        self.lineEdit_210.setObjectName("lineEdit_210")
        self.lineEdit_109 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_109.setGeometry(QtCore.QRect(234, 620, 61, 20))
        self.lineEdit_109.setObjectName("lineEdit_109")
        self.label_22 = QtWidgets.QLabel(Steel)
        self.label_22.setGeometry(QtCore.QRect(200, 620, 21, 20))
        self.label_22.setObjectName("label_22")
        self.plainTextEdit_angle = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit_angle.setGeometry(QtCore.QRect(284, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_angle.setFont(font)
        self.plainTextEdit_angle.setObjectName("plainTextEdit_angle")
        self.label_23 = QtWidgets.QLabel(Steel)
        self.label_23.setGeometry(QtCore.QRect(400, 440, 21, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Steel)
        self.label_24.setGeometry(QtCore.QRect(200, 680, 21, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_108 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_108.setGeometry(QtCore.QRect(234, 590, 61, 20))
        self.lineEdit_108.setObjectName("lineEdit_108")
        self.lineEdit_104 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_104.setGeometry(QtCore.QRect(234, 470, 61, 20))
        self.lineEdit_104.setObjectName("lineEdit_104")
        self.label_25 = QtWidgets.QLabel(Steel)
        self.label_25.setGeometry(QtCore.QRect(380, 530, 41, 20))
        self.label_25.setObjectName("label_25")
        self.pushButton_a_add = QtWidgets.QPushButton(Steel)
        self.pushButton_a_add.setGeometry(QtCore.QRect(154, 110, 75, 23))
        self.pushButton_a_add.setObjectName("pushButton_a_add")
        self.label_26 = QtWidgets.QLabel(Steel)
        self.label_26.setGeometry(QtCore.QRect(380, 410, 41, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Steel)
        self.label_27.setGeometry(QtCore.QRect(194, 590, 31, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Steel)
        self.label_28.setGeometry(QtCore.QRect(190, 410, 31, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Steel)
        self.label_29.setGeometry(QtCore.QRect(201, 560, 20, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_110 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_110.setGeometry(QtCore.QRect(234, 650, 61, 20))
        self.lineEdit_110.setObjectName("lineEdit_110")
        self.lineEdit_101 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_101.setGeometry(QtCore.QRect(234, 380, 61, 20))
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.lineEdit_105 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_105.setGeometry(QtCore.QRect(234, 500, 61, 20))
        self.lineEdit_105.setObjectName("lineEdit_105")
        self.lineEdit_102 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_102.setGeometry(QtCore.QRect(234, 410, 61, 20))
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.label_30 = QtWidgets.QLabel(Steel)
        self.label_30.setGeometry(QtCore.QRect(201, 500, 20, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Steel)
        self.label_31.setGeometry(QtCore.QRect(190, 650, 31, 20))
        self.label_31.setObjectName("label_31")
        self.pushButton_a_cf = QtWidgets.QPushButton(Steel)
        self.pushButton_a_cf.setGeometry(QtCore.QRect(154, 80, 75, 23))
        self.pushButton_a_cf.setObjectName("pushButton_a_cf")
        self.pushButton_a_update = QtWidgets.QPushButton(Steel)
        self.pushButton_a_update.setGeometry(QtCore.QRect(154, 50, 75, 23))
        self.pushButton_a_update.setObjectName("pushButton_a_update")
        self.label_32 = QtWidgets.QLabel(Steel)
        self.label_32.setGeometry(QtCore.QRect(200, 350, 21, 20))
        self.label_32.setObjectName("label_32")
        self.lineEdit_106 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_106.setGeometry(QtCore.QRect(234, 530, 61, 20))
        self.lineEdit_106.setObjectName("lineEdit_106")
        self.label_33 = QtWidgets.QLabel(Steel)
        self.label_33.setGeometry(QtCore.QRect(380, 500, 41, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Steel)
        self.label_34.setGeometry(QtCore.QRect(394, 560, 31, 20))
        self.label_34.setObjectName("label_34")
        self.lineEdit_103 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_103.setGeometry(QtCore.QRect(234, 440, 61, 20))
        self.lineEdit_103.setObjectName("lineEdit_103")
        self.label_35 = QtWidgets.QLabel(Steel)
        self.label_35.setGeometry(QtCore.QRect(164, 370, 61, 31))
        self.label_35.setObjectName("label_35")
        self.lineEdit_107 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_107.setGeometry(QtCore.QRect(234, 560, 61, 20))
        self.lineEdit_107.setObjectName("lineEdit_107")
        self.label_36 = QtWidgets.QLabel(Steel)
        self.label_36.setGeometry(QtCore.QRect(200, 530, 21, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Steel)
        self.label_37.setGeometry(QtCore.QRect(400, 470, 21, 20))
        self.label_37.setObjectName("label_37")
        self.lineEdit_111 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_111.setGeometry(QtCore.QRect(234, 680, 61, 20))
        self.lineEdit_111.setObjectName("lineEdit_111")
        self.label_38 = QtWidgets.QLabel(Steel)
        self.label_38.setGeometry(QtCore.QRect(324, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Steel)
        self.label_39.setGeometry(QtCore.QRect(190, 440, 31, 20))
        self.label_39.setObjectName("label_39")
        self.pushButton_a_import = QtWidgets.QPushButton(Steel)
        self.pushButton_a_import.setGeometry(QtCore.QRect(154, 140, 75, 23))
        self.pushButton_a_import.setObjectName("pushButton_a_import")
        self.label_40 = QtWidgets.QLabel(Steel)
        self.label_40.setGeometry(QtCore.QRect(190, 470, 31, 20))
        self.label_40.setObjectName("label_40")
        self.lineEdit_100 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_100.setGeometry(QtCore.QRect(234, 350, 61, 20))
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.label_41 = QtWidgets.QLabel(Steel)
        self.label_41.setGeometry(QtCore.QRect(400, 350, 21, 20))
        self.label_41.setObjectName("label_41")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(464, 50, 20, 281))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.label_42 = QtWidgets.QLabel(Steel)
        self.label_42.setGeometry(QtCore.QRect(380, 380, 41, 20))
        self.label_42.setObjectName("label_42")
        self.lineEdit_309 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_309.setGeometry(QtCore.QRect(1084, 620, 61, 20))
        self.lineEdit_309.setObjectName("lineEdit_309")
        self.label_43 = QtWidgets.QLabel(Steel)
        self.label_43.setGeometry(QtCore.QRect(1050, 620, 21, 20))
        self.label_43.setObjectName("label_43")
        self.plainTextEdit_channel = QtWidgets.QPlainTextEdit(Steel)
        self.plainTextEdit_channel.setGeometry(QtCore.QRect(1124, 50, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_channel.setFont(font)
        self.plainTextEdit_channel.setObjectName("plainTextEdit_channel")
        self.label_44 = QtWidgets.QLabel(Steel)
        self.label_44.setGeometry(QtCore.QRect(1250, 500, 21, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(Steel)
        self.label_45.setGeometry(QtCore.QRect(1250, 380, 21, 20))
        self.label_45.setObjectName("label_45")
        self.lineEdit_308 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_308.setGeometry(QtCore.QRect(1084, 590, 61, 20))
        self.lineEdit_308.setObjectName("lineEdit_308")
        self.lineEdit_317 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_317.setGeometry(QtCore.QRect(1284, 530, 61, 20))
        self.lineEdit_317.setObjectName("lineEdit_317")
        self.lineEdit_304 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_304.setGeometry(QtCore.QRect(1084, 470, 61, 20))
        self.lineEdit_304.setObjectName("lineEdit_304")
        self.label_46 = QtWidgets.QLabel(Steel)
        self.label_46.setGeometry(QtCore.QRect(1251, 590, 20, 20))
        self.label_46.setObjectName("label_46")
        self.pushButton_c_add = QtWidgets.QPushButton(Steel)
        self.pushButton_c_add.setGeometry(QtCore.QRect(994, 110, 75, 23))
        self.pushButton_c_add.setObjectName("pushButton_c_add")
        self.label_47 = QtWidgets.QLabel(Steel)
        self.label_47.setGeometry(QtCore.QRect(1250, 470, 21, 20))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(Steel)
        self.label_48.setGeometry(QtCore.QRect(1014, 590, 61, 20))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Steel)
        self.label_49.setGeometry(QtCore.QRect(1040, 410, 31, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(Steel)
        self.label_50.setGeometry(QtCore.QRect(1051, 560, 20, 20))
        self.label_50.setObjectName("label_50")
        self.lineEdit_311 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_311.setGeometry(QtCore.QRect(1284, 350, 61, 20))
        self.lineEdit_311.setObjectName("lineEdit_311")
        self.lineEdit_301 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_301.setGeometry(QtCore.QRect(1084, 380, 61, 20))
        self.lineEdit_301.setObjectName("lineEdit_301")
        self.lineEdit_305 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_305.setGeometry(QtCore.QRect(1084, 500, 61, 20))
        self.lineEdit_305.setObjectName("lineEdit_305")
        self.lineEdit_302 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_302.setGeometry(QtCore.QRect(1084, 410, 61, 20))
        self.lineEdit_302.setObjectName("lineEdit_302")
        self.label_51 = QtWidgets.QLabel(Steel)
        self.label_51.setGeometry(QtCore.QRect(1051, 500, 20, 20))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Steel)
        self.label_52.setGeometry(QtCore.QRect(1250, 350, 21, 20))
        self.label_52.setObjectName("label_52")
        self.lineEdit_319 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_319.setGeometry(QtCore.QRect(1284, 590, 61, 20))
        self.lineEdit_319.setObjectName("lineEdit_319")
        self.pushButton_c_cf = QtWidgets.QPushButton(Steel)
        self.pushButton_c_cf.setGeometry(QtCore.QRect(994, 80, 75, 23))
        self.pushButton_c_cf.setObjectName("pushButton_c_cf")
        self.pushButton_c_update = QtWidgets.QPushButton(Steel)
        self.pushButton_c_update.setGeometry(QtCore.QRect(994, 50, 75, 23))
        self.pushButton_c_update.setObjectName("pushButton_c_update")
        self.label_53 = QtWidgets.QLabel(Steel)
        self.label_53.setGeometry(QtCore.QRect(1050, 350, 21, 20))
        self.label_53.setObjectName("label_53")
        self.lineEdit_306 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_306.setGeometry(QtCore.QRect(1084, 530, 61, 20))
        self.lineEdit_306.setObjectName("lineEdit_306")
        self.label_54 = QtWidgets.QLabel(Steel)
        self.label_54.setGeometry(QtCore.QRect(1250, 560, 21, 20))
        self.label_54.setObjectName("label_54")
        self.lineEdit_316 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_316.setGeometry(QtCore.QRect(1284, 500, 61, 20))
        self.lineEdit_316.setObjectName("lineEdit_316")
        self.label_55 = QtWidgets.QLabel(Steel)
        self.label_55.setGeometry(QtCore.QRect(1234, 620, 41, 20))
        self.label_55.setObjectName("label_55")
        self.lineEdit_303 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_303.setGeometry(QtCore.QRect(1084, 440, 61, 20))
        self.lineEdit_303.setObjectName("lineEdit_303")
        self.label_56 = QtWidgets.QLabel(Steel)
        self.label_56.setGeometry(QtCore.QRect(1014, 370, 61, 31))
        self.label_56.setObjectName("label_56")
        self.lineEdit_314 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_314.setGeometry(QtCore.QRect(1284, 440, 61, 20))
        self.lineEdit_314.setObjectName("lineEdit_314")
        self.lineEdit_307 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_307.setGeometry(QtCore.QRect(1084, 560, 61, 20))
        self.lineEdit_307.setObjectName("lineEdit_307")
        self.label_57 = QtWidgets.QLabel(Steel)
        self.label_57.setGeometry(QtCore.QRect(1050, 530, 21, 20))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Steel)
        self.label_58.setGeometry(QtCore.QRect(1250, 530, 21, 20))
        self.label_58.setObjectName("label_58")
        self.lineEdit_318 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_318.setGeometry(QtCore.QRect(1284, 560, 61, 20))
        self.lineEdit_318.setObjectName("lineEdit_318")
        self.lineEdit_312 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_312.setGeometry(QtCore.QRect(1284, 380, 61, 20))
        self.lineEdit_312.setObjectName("lineEdit_312")
        self.lineEdit_313 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_313.setGeometry(QtCore.QRect(1284, 410, 61, 20))
        self.lineEdit_313.setObjectName("lineEdit_313")
        self.label_59 = QtWidgets.QLabel(Steel)
        self.label_59.setGeometry(QtCore.QRect(1164, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.lineEdit_320 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_320.setGeometry(QtCore.QRect(1284, 620, 61, 20))
        self.lineEdit_320.setObjectName("lineEdit_320")
        self.label_60 = QtWidgets.QLabel(Steel)
        self.label_60.setGeometry(QtCore.QRect(1040, 440, 31, 20))
        self.label_60.setObjectName("label_60")
        self.pushButton_c_import = QtWidgets.QPushButton(Steel)
        self.pushButton_c_import.setGeometry(QtCore.QRect(994, 140, 75, 23))
        self.pushButton_c_import.setObjectName("pushButton_c_import")
        self.label_61 = QtWidgets.QLabel(Steel)
        self.label_61.setGeometry(QtCore.QRect(1051, 470, 20, 20))
        self.label_61.setObjectName("label_61")
        self.lineEdit_300 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_300.setGeometry(QtCore.QRect(1084, 350, 61, 20))
        self.lineEdit_300.setObjectName("lineEdit_300")
        self.label_62 = QtWidgets.QLabel(Steel)
        self.label_62.setGeometry(QtCore.QRect(1250, 410, 21, 20))
        self.label_62.setObjectName("label_62")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(Steel)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(1304, 50, 20, 281))
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.lineEdit_315 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_315.setGeometry(QtCore.QRect(1284, 470, 61, 20))
        self.lineEdit_315.setObjectName("lineEdit_315")
        self.label_63 = QtWidgets.QLabel(Steel)
        self.label_63.setGeometry(QtCore.QRect(1250, 440, 21, 20))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(Steel)
        self.label_64.setGeometry(QtCore.QRect(340, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(Steel)
        self.label_65.setGeometry(QtCore.QRect(760, 10, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(Steel)
        self.label_66.setGeometry(QtCore.QRect(1190, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.line = QtWidgets.QFrame(Steel)
        self.line.setGeometry(QtCore.QRect(523, 0, 20, 711))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Steel)
        self.line_2.setGeometry(QtCore.QRect(950, -10, 20, 721))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Steel)
        self.line_3.setGeometry(QtCore.QRect(110, -10, 20, 721))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_120 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_120.setGeometry(QtCore.QRect(430, 590, 61, 20))
        self.lineEdit_120.setObjectName("lineEdit_120")
        self.lineEdit_113 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_113.setGeometry(QtCore.QRect(430, 380, 61, 20))
        self.lineEdit_113.setObjectName("lineEdit_113")
        self.lineEdit_121 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_121.setGeometry(QtCore.QRect(430, 620, 61, 20))
        self.lineEdit_121.setObjectName("lineEdit_121")
        self.lineEdit_123 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_123.setGeometry(QtCore.QRect(430, 680, 61, 20))
        self.lineEdit_123.setObjectName("lineEdit_123")
        self.lineEdit_112 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_112.setGeometry(QtCore.QRect(430, 350, 61, 20))
        self.lineEdit_112.setObjectName("lineEdit_112")
        self.lineEdit_114 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_114.setGeometry(QtCore.QRect(430, 410, 61, 20))
        self.lineEdit_114.setObjectName("lineEdit_114")
        self.lineEdit_122 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_122.setGeometry(QtCore.QRect(430, 650, 61, 20))
        self.lineEdit_122.setObjectName("lineEdit_122")
        self.lineEdit_119 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_119.setGeometry(QtCore.QRect(430, 560, 61, 20))
        self.lineEdit_119.setObjectName("lineEdit_119")
        self.lineEdit_117 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_117.setGeometry(QtCore.QRect(430, 500, 61, 20))
        self.lineEdit_117.setObjectName("lineEdit_117")
        self.lineEdit_116 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_116.setGeometry(QtCore.QRect(430, 470, 61, 20))
        self.lineEdit_116.setObjectName("lineEdit_116")
        self.lineEdit_118 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_118.setGeometry(QtCore.QRect(430, 530, 61, 20))
        self.lineEdit_118.setObjectName("lineEdit_118")
        self.lineEdit_115 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_115.setGeometry(QtCore.QRect(430, 440, 61, 20))
        self.lineEdit_115.setObjectName("lineEdit_115")
        self.label_67 = QtWidgets.QLabel(Steel)
        self.label_67.setGeometry(QtCore.QRect(396, 590, 21, 20))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(Steel)
        self.label_68.setGeometry(QtCore.QRect(396, 620, 21, 20))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(Steel)
        self.label_69.setGeometry(QtCore.QRect(390, 650, 20, 20))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(Steel)
        self.label_70.setGeometry(QtCore.QRect(380, 680, 41, 20))
        self.label_70.setObjectName("label_70")
        self.lineEdit_310 = QtWidgets.QLineEdit(Steel)
        self.lineEdit_310.setGeometry(QtCore.QRect(1084, 650, 61, 20))
        self.lineEdit_310.setObjectName("lineEdit_310")
        self.label_71 = QtWidgets.QLabel(Steel)
        self.label_71.setGeometry(QtCore.QRect(1050, 650, 21, 20))
        self.label_71.setObjectName("label_71")
        self.pushButton_exit = QtWidgets.QPushButton(Steel)
        self.pushButton_exit.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Steel)
        QtCore.QMetaObject.connectSlotsByName(Steel)

    def retranslateUi(self, Steel):
        _translate = QtCore.QCoreApplication.translate
        Steel.setWindowTitle(_translate("Steel", "Steel Section"))
        self.pushButton_loaddata.setText(_translate("Steel", "Load Data"))
        self.pushButton_b_update.setText(_translate("Steel", "Update"))
        self.label.setText(_translate("Steel", "ID"))
        self.label_2.setText(_translate("Steel", "Designation"))
        self.label_3.setText(_translate("Steel", "Mass"))
        self.label_4.setText(_translate("Steel", "Area"))
        self.label_5.setText(_translate("Steel", "D"))
        self.label_6.setText(_translate("Steel", "B"))
        self.label_7.setText(_translate("Steel", "tw"))
        self.label_8.setText(_translate("Steel", "T"))
        self.label_9.setText(_translate("Steel", "FlangeSlope"))
        self.label_10.setText(_translate("Steel", "R1"))
        self.label_11.setText(_translate("Steel", "rz"))
        self.label_12.setText(_translate("Steel", "ry"))
        self.label_13.setText(_translate("Steel", "Source"))
        self.label_14.setText(_translate("Steel", "Zpz"))
        self.label_15.setText(_translate("Steel", "Zy"))
        self.label_16.setText(_translate("Steel", "ly"))
        self.label_17.setText(_translate("Steel", "Zpy"))
        self.label_18.setText(_translate("Steel", "Zz"))
        self.label_19.setText(_translate("Steel", "lz"))
        self.label_20.setText(_translate("Steel", "R2"))
        self.label_21.setText(_translate("Steel", "   Designation"))
        self.pushButton_b_add.setText(_translate("Steel", "Add"))
        self.pushButton_b_import.setText(_translate("Steel", "Import"))
        self.pushButton_b_cf.setText(_translate("Steel", "Clear Field"))
        self.label_22.setText(_translate("Steel", "Cy"))
        self.label_23.setText(_translate("Steel", "rz"))
        self.label_24.setText(_translate("Steel", "lz"))
        self.label_25.setText(_translate("Steel", "ru(min)"))
        self.pushButton_a_add.setText(_translate("Steel", "Add"))
        self.label_26.setText(_translate("Steel", "lv(min)"))
        self.label_27.setText(_translate("Steel", "  Cz"))
        self.label_28.setText(_translate("Steel", "Mass"))
        self.label_29.setText(_translate("Steel", "R2"))
        self.label_30.setText(_translate("Steel", "t"))
        self.label_31.setText(_translate("Steel", "Tan?"))
        self.pushButton_a_cf.setText(_translate("Steel", "Clear Field"))
        self.pushButton_a_update.setText(_translate("Steel", "Update"))
        self.label_32.setText(_translate("Steel", "ID"))
        self.label_33.setText(_translate("Steel", "ru(max)"))
        self.label_34.setText(_translate("Steel", "Zz"))
        self.label_35.setText(_translate("Steel", "Designation"))
        self.label_36.setText(_translate("Steel", "R1"))
        self.label_37.setText(_translate("Steel", "ry"))
        self.label_38.setText(_translate("Steel", "   Designation"))
        self.label_39.setText(_translate("Steel", "Area"))
        self.pushButton_a_import.setText(_translate("Steel", "Import"))
        self.label_40.setText(_translate("Steel", "AXB"))
        self.label_41.setText(_translate("Steel", "ly"))
        self.label_42.setText(_translate("Steel", "lu(max)"))
        self.label_43.setText(_translate("Steel", "R1"))
        self.label_44.setText(_translate("Steel", "Zz"))
        self.label_45.setText(_translate("Steel", "lz"))
        self.label_46.setText(_translate("Steel", "Zpy"))
        self.pushButton_c_add.setText(_translate("Steel", "Add"))
        self.label_47.setText(_translate("Steel", "ry"))
        self.label_48.setText(_translate("Steel", "FlangeSlope"))
        self.label_49.setText(_translate("Steel", "Mass"))
        self.label_50.setText(_translate("Steel", "T"))
        self.label_51.setText(_translate("Steel", "B"))
        self.label_52.setText(_translate("Steel", "R2"))
        self.pushButton_c_cf.setText(_translate("Steel", "Clear Field"))
        self.pushButton_c_update.setText(_translate("Steel", "Update"))
        self.label_53.setText(_translate("Steel", "ID"))
        self.label_54.setText(_translate("Steel", "Zpz"))
        self.label_55.setText(_translate("Steel", "Source"))
        self.label_56.setText(_translate("Steel", "Designation"))
        self.label_57.setText(_translate("Steel", "tw"))
        self.label_58.setText(_translate("Steel", "Zy"))
        self.label_59.setText(_translate("Steel", "   Designation"))
        self.label_60.setText(_translate("Steel", "Area"))
        self.pushButton_c_import.setText(_translate("Steel", "Import"))
        self.label_61.setText(_translate("Steel", "D"))
        self.label_62.setText(_translate("Steel", "ly"))
        self.label_63.setText(_translate("Steel", "rz"))
        self.label_64.setText(_translate("Steel", "   Angles"))
        self.label_65.setText(_translate("Steel", "  Beams"))
        self.label_66.setText(_translate("Steel", "Channels"))
        self.label_67.setText(_translate("Steel", "Zy"))
        self.label_68.setText(_translate("Steel", "Zpz"))
        self.label_69.setText(_translate("Steel", "Zpy"))
        self.label_70.setText(_translate("Steel", "Source"))
        self.label_71.setText(_translate("Steel", "Cy"))
        self.pushButton_exit.setText(_translate("Steel", "Exit"))

